/**
 * Lista de domínios de email descartáveis/temporários
 * Bloqueia registos com estes domínios para prevenir fraude
 */

const DISPOSABLE_DOMAINS: Set<string> = new Set([
  // Serviços populares de email temporário
  'guerrillamail.com',
  'guerrillamail.de',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamailblock.com',
  'grr.la',
  'tempmail.com',
  'temp-mail.org',
  'temp-mail.io',
  'tempail.com',
  'tempr.email',
  'tempinbox.com',
  'mailinator.com',
  'mailinator2.com',
  'maildrop.cc',
  'mailnesia.com',
  'mailsac.com',
  'yopmail.com',
  'yopmail.fr',
  'yopmail.net',
  'throwaway.email',
  'throwawaymail.com',
  'sharklasers.com',
  'guerrillamailblock.com',
  'dispostable.com',
  'trashmail.com',
  'trashmail.me',
  'trashmail.net',
  'trashymail.com',
  'fakeinbox.com',
  'fakemail.net',
  'getnada.com',
  'getairmail.com',
  'mailnull.com',
  'mailcatch.com',
  'harakirimail.com',
  'mytemp.email',
  'mt2015.com',
  'mohmal.com',
  'discard.email',
  'discardmail.com',
  'discardmail.de',
  'emailondeck.com',
  'inboxbear.com',
  'mintemail.com',
  'spamgourmet.com',
  'spamfree24.org',
  'safetymail.info',
  'binkmail.com',
  'bobmail.info',
  'burnthismail.com',
  'curryworld.de',
  'dayrep.com',
  'einrot.de',
  'emailigo.de',
  'emailtemporario.com.br',
  'ephemail.net',
  'filzmail.com',
  'fixmail.tk',
  'flurred.com',
  'jetable.org',
  'kasmail.com',
  'koszmail.pl',
  'kurzepost.de',
  'mailexpire.com',
  'mailforspam.com',
  'mailhazard.com',
  'mailmoat.com',
  'mailscrap.com',
  'mailshell.com',
  'mailsiphon.com',
  'mailtemp.info',
  'mailzilla.com',
  'nomail.xl.cx',
  'nowmymail.com',
  'obobbo.com',
  'onewaymail.com',
  'owlpic.com',
  'pookmail.com',
  'proxymail.eu',
  'rcpt.at',
  'reallymymail.com',
  'recode.me',
  'regbypass.com',
  'rhyta.com',
  'rklips.com',
  'rmqkr.net',
  'royal.net',
  'safersignup.de',
  'saynotospams.com',
  'selfdestructingmail.com',
  'shortmail.net',
  'sibmail.com',
  'soodonims.com',
  'spambob.com',
  'spambob.net',
  'spambob.org',
  'spaml.de',
  'superrito.com',
  'suremail.info',
  'teleworm.us',
  'tempalias.com',
  'tempemail.co.za',
  'tempe-mail.com',
  'tempinbox.co.uk',
  'tempmaildemo.com',
  'tempmailer.com',
  'tempomail.fr',
  'temporarily.de',
  'temporarioemail.com.br',
  'temporaryemail.net',
  'temporaryforwarding.com',
  'temporaryinbox.com',
  'temporarymailaddress.com',
  'thanksnospam.info',
  'thankyou2010.com',
  'thisisnotmyrealemail.com',
  'trashdevil.com',
  'trashdevil.de',
  'trashemail.de',
  'uglymailbox.com',
  'wegwerfmail.de',
  'wegwerfmail.net',
  'wegwerfmail.org',
  'wh4f.org',
  'whyspam.me',
  'willhackforfood.biz',
  'willselfdestruct.com',
  'wuzupmail.net',
  'xagloo.com',
  'xemne.com',
  'xents.com',
  'xjoi.com',
  'xoxy.net',
  'zetmail.com',
  'zippymail.info',
  'zoaxe.com',
  'zoemail.org',
  // 10minutemail e variações
  '10minutemail.com',
  '10minutemail.co.za',
  '10minutemail.de',
  '20minutemail.com',
  '20minutemail.it',
  // Mailbox temporárias brasileiras
  'emailfake.com',
  'crazymailing.com',
  'luxusmail.org',
]);

/**
 * Verifica se um email usa um domínio descartável
 * @param email - Endereço de email completo
 * @returns true se o domínio é descartável (deve ser bloqueado)
 */
export function isDisposableEmail(email: string): boolean {
  if (!email || !email.includes('@')) return false;

  const domain = email.split('@')[1]?.toLowerCase().trim();
  if (!domain) return false;

  return DISPOSABLE_DOMAINS.has(domain);
}
